# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVJaoNvwq7QgsDeIKzxILyMdyKXjMze7
"""

import numpy as np
import matplotlib.pyplot as plt

u = 1.0 
dt = 0.1
dx = 1.0
x = np.arange(0, 100+dx, dx)
t = np.arange(0, 1000+dt, dt)
func = np.zeros(x.shape[0])
func[40:60] = 1

fx=np.copy(func)

for iter in t:
    c = fx
    b = 1/(2*dx)*(np.roll(fx,-1,0)-np.roll(fx,1,0))
    a = 1/(2*dx**2)*(np.roll(fx,-1,0)-2*fx+np.roll(fx,1,0))
    fx = a*(C*dx)**2-b*(C*dx)+c

    if iter==10:
        plt.plot(x,fx, label= f't = {iter}')
        plt.legend()
    if iter==200: 
        plt.plot(x,fx, label= f't = {iter}')
        plt.legend()
    if iter==400: 
        plt.plot(x,fx, label= f't = {iter}')
        plt.legend()
    if iter==600: 
        plt.plot(x,fx, label= f't = {iter}')
        plt.legend()