# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcqdfRFkaEMKT574K0ErOCaO9hSTh0Hg
"""

import numpy as np
import matplotlib.pyplot as plt

len_x = 100.0
len_y = 100.0
v = 1
n=0
dx = dy = 1.0
dt = 0.01
end_time = 100
x = np.arange(0.0,len_x+dx,dx)
y = np.arange(0.0,len_y+dy,dy)
X,Y = np.meshgrid(x,y)

u = np.zeros((y.shape[0],x.shape[0]))
u[5:50,10:60] = 20.0

for it in np.arange(0.0,end_time + dt,dt):
    a=u
    #a=1
    u = u + (dt/dx) * (a * (np.roll(u,1,1)+np.roll(u,1,0)-2*u) + v/dx * (np.roll(u,-1,1)+np.roll(u,+1,1)+np.roll(u,-1,0)+np.roll(u,+1,0)-4*u))
    if n%30==0:
        fig = plt.figure()
        ax = plt.axes(projection='3d')
        ax.plot_surface(X, Y, u, cmap='rainbow', linewidth=0)
        ax.view_init(20,80)
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_zlabel('u')
        plt.savefig('test_%05i.png'%(n/30))
        plt.cla()
        plt.clf()
    n+=1
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, u, cmap='rainbow', linewidth=0)
ax.view_init(20,80)
ax.set_ylabel('y')
ax.set_zlabel('u')